name: Deploy Workflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/${{ secrets.USERNAME }}/koolskool
            git pull
            sudo systemctl restart nginx
            sudo systemctl restart homesite.service
